"""Agent layer Dockerfile generation.

This module generates a Dockerfile that adds the CLI agent to a base image.
The agent is installed at user-side build time (not in the published image)
due to licensing restrictions that may prohibit redistribution.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from paude.constants import CONTAINER_ENTRYPOINT, CONTAINER_HOME

if TYPE_CHECKING:
    from paude.agents.base import Agent, AgentComposition


def generate_claude_layer_dockerfile(
    agent: Agent | None = None,
    composition: AgentComposition | None = None,
) -> str:
    """Generate a Dockerfile that adds the CLI agent to a base image.

    Args:
        agent: Agent instance. If None, uses Claude defaults.

    Returns:
        Dockerfile content that installs the agent on top of BASE_IMAGE.
    """
    if composition is None and agent is None:
        from paude.agents import get_agent

        agent = get_agent("claude")

    from paude.agents import (
        dockerfile_install_lines_for_agent,
        dockerfile_install_lines_for_composition,
    )

    lines: list[str] = []

    lines.append("# Auto-generated by paude - DO NOT EDIT")
    if composition is not None:
        primary = composition.primary
    elif agent is not None:
        primary = agent
    else:
        raise ValueError("An agent is required when no composition is provided")
    display = primary.config.display_name
    lines.append(f"# This layer adds {display} to the base paude image")
    lines.append("ARG BASE_IMAGE")
    lines.append("FROM ${BASE_IMAGE}")
    lines.append("")
    lines.append("USER root")

    # The explicit composition is already resolved; the single-agent path
    # retains its historical bundled-agent expansion.
    if composition is not None:
        lines.extend(
            dockerfile_install_lines_for_composition(composition, CONTAINER_HOME)
        )
    elif agent is not None:
        lines.extend(dockerfile_install_lines_for_agent(agent, CONTAINER_HOME))
    else:
        raise ValueError("An agent is required when no composition is provided")

    lines.append(f'ENTRYPOINT ["{CONTAINER_ENTRYPOINT}"]')

    return "\n".join(lines)
