"""Dockerfile generation for paude."""

from __future__ import annotations

from paude.config.models import PaudeConfig


def generate_workspace_dockerfile(config: PaudeConfig) -> str:
    """Generate a Dockerfile that wraps the user's base image with paude requirements.

    This output matches the bash generate_workspace_dockerfile() function exactly.

    Args:
        config: Parsed paude configuration.

    Returns:
        Generated Dockerfile content.
    """
    lines: list[str] = []

    # Header
    lines.append("# Auto-generated by paude - DO NOT EDIT")
    lines.append("ARG BASE_IMAGE")
    lines.append("FROM ${BASE_IMAGE}")

    # Add user-specified packages if any (from paude.json "packages" array)
    if config.packages:
        pkg_list = " ".join(config.packages)
        lines.append("")
        lines.append("# User-specified packages from paude.json")
        lines.append(f"""RUN if command -v apt-get >/dev/null 2>&1; then \\
        apt-get update && apt-get install -y {pkg_list} && rm -rf /var/lib/apt/lists/*; \\
    elif command -v apk >/dev/null 2>&1; then \\
        apk add --no-cache {pkg_list}; \\
    elif command -v yum >/dev/null 2>&1; then \\
        yum install -y {pkg_list} && yum clean all; \\
    fi""")

    # Standard paude requirements
    lines.append("")
    lines.append("""# Install required system packages
RUN if command -v apt-get >/dev/null 2>&1; then \\
        apt-get update && \\
        apt-get install -y --no-install-recommends git curl ca-certificates && \\
        rm -rf /var/lib/apt/lists/*; \\
    elif command -v apk >/dev/null 2>&1; then \\
        apk add --no-cache git curl ca-certificates; \\
    elif command -v yum >/dev/null 2>&1; then \\
        yum install -y git curl ca-certificates && \\
        yum clean all; \\
    else \\
        echo "Warning: Unknown package manager, git may not be available" >&2; \\
    fi""")

    lines.append("")
    lines.append("""# Install Node.js if not present (required for claude-code)
RUN if ! command -v node >/dev/null 2>&1; then \\
        if command -v apt-get >/dev/null 2>&1; then \\
            curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \\
            apt-get install -y nodejs && \\
            rm -rf /var/lib/apt/lists/*; \\
        elif command -v apk >/dev/null 2>&1; then \\
            apk add --no-cache nodejs npm; \\
        else \\
            echo "Error: Cannot install Node.js - unsupported base image" >&2 && exit 1; \\
        fi \\
    fi""")

    lines.append("")
    lines.append("# Install Claude Code")
    lines.append("RUN npm install -g @anthropic-ai/claude-code")

    lines.append("")
    lines.append("# Create paude user if it doesn't exist")
    lines.append(
        "RUN id paude >/dev/null 2>&1 || useradd -m -s /bin/bash paude 2>/dev/null || adduser -D -s /bin/bash paude"
    )

    if config.pip_install:
        lines.append("")
        lines.append("# Build-time pip install for venv isolation")
        lines.append("COPY . /opt/workspace-src")
        lines.append("RUN python3 -m venv /opt/venv")

        if isinstance(config.pip_install, str):
            pip_cmd = config.pip_install
        else:
            pip_cmd = "pip install -e /opt/workspace-src"

        lines.append(f"RUN /opt/venv/bin/{pip_cmd}")
        lines.append("RUN chown -R paude:paude /opt/venv")

    lines.append("")
    lines.append("# Copy entrypoint")
    lines.append("COPY entrypoint.sh /usr/local/bin/entrypoint.sh")
    lines.append("RUN chmod +x /usr/local/bin/entrypoint.sh")

    lines.append("")
    lines.append("USER paude")
    lines.append("ENTRYPOINT [\"/usr/local/bin/entrypoint.sh\"]")

    return "\n".join(lines)
